apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-mlops-app
  labels:
    app: titanic-mlops-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: titanic-mlops-app
  template:
    metadata:
      labels:
        app: titanic-mlops-app
    spec:
      containers:
        - name: titanic-mlops-app
          image: nancyaneesh/titanic-mlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_PATH
              value: "models/best_model.pkl"
            - name: FLASK_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"