apiVersion: v1
kind: Service
metadata:
  name: titanic-mlops-service
spec:
  type: NodePort
  selector:
    app: titanic-mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080