name: Kubernetes Deployment Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-to-kind:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # Checkout repository
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # Set up Docker Buildx
      # =========================
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # =========================
      # Install kubectl
      # =========================
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      # =========================
      # Create KIND cluster
      # =========================
      - name: Create local Kubernetes cluster using Kind
        uses: helm/kind-action@v1.10.0

      # =========================
      # Build Docker image
      # =========================
      - name: Build Docker image
        run: |
          docker build -t titanic-mlops-app:latest .

      # =========================
      # Load image into KIND
      # =========================
      - name: Load Docker image into Kind
        run: |
          kind load docker-image titanic-mlops-app:latest

      # =========================
      # Deploy Kubernetes manifests
      # =========================
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml

      # =========================
      # Wait for deployment
      # =========================
      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/titanic-mlops-app

      # =========================
      # Check Kubernetes resources
      # =========================
      - name: Check Kubernetes deployment
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get hpa

      # =========================
      # Port forward application
      # =========================
      - name: Start port forwarding
        run: |
          kubectl port-forward service/titanic-mlops-service 5000:80 &
          sleep 15

      # =========================
      # Health check
      # =========================
      - name: Health check
        run: |
          curl http://localhost:5000/health

      # =========================
      # API test
      # =========================
      - name: Prediction API test
        run: |
          curl -X POST http://localhost:5000/predict \
          -H "Content-Type: application/json" \
          -d '{"Pclass":3,"Sex":"male","Age":22,"Fare":7.25,"Embarked":"S"}'