  kubernetes-deployment:
    needs: docker-build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate Kubernetes deployment manifest
        run: |
          kubectl create --dry-run=client --validate=false -f k8s/deployment.yaml

      - name: Validate Kubernetes service manifest
        run: |
          kubectl create --dry-run=client --validate=false -f k8s/service.yaml

      - name: Validate Kubernetes HPA manifest
        run: |
          kubectl create --dry-run=client --validate=false -f k8s/hpa.yaml